version: '3'

services:
    app:
        build: .
        restart: unless-stopped
        volumes:
            - ./src:/var/www
        networks:
            - app-network
        ports:
            - "3000:3000"
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www
        ports:
            - "80:80"
        networks:
            - app-network
    db:
        image: percona:latest
        restart: unless-stopped
        volumes:
            - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "db"
            MYSQL_DATABASE: "cube"
            MYSQL_USER: "db"
            MYSQL_PASSWORD: "db"
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
