version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - app-network
    vite:
        image: node:16-alpine
        volumes:
            - ./:/var/www
        ports:
            - "3000:3000"
        working_dir: /var/www
        networks:
            - app-network
        command: sh -c "npm run dev"
    npm:
        image: node:18-alpine
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
    db:
        image: percona:latest
        platform: linux/amd64
        restart: unless-stopped
        volumes:
            - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "db"
            MYSQL_DATABASE: "cube"
            MYSQL_USER: "db"
            MYSQL_PASSWORD: "db"
        ports:
            - "3306:3306"
        networks:
            - app-network

volumes:
    db:

networks:
    app-network:
