#!/usr/bin/env bash

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

if [ "$env" = "local" ]; then
    cd /var/www && php artisan config:cache && php artisan route:cache && php artisan view:cache
fi

# @TODO start horizon

if [ "$role" = "app" ]; then
    echo "Starting cron..."
    cron
    echo "Cron started!"
    echo "Starting app..."
    exec php-fpm
fi
